"""empty message

Revision ID: 23a1b3bfe870
Revises: eff350cf616b
Create Date: 2022-01-02 18:28:43.945129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a1b3bfe870'
down_revision = 'eff350cf616b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cn_note_author_id_fkey', 'cn_note', type_='foreignkey')
    op.create_foreign_key(None, 'cn_note', 'cn_account', ['author_id'], ['id'], ondelete='cascade')
    op.drop_constraint('cn_tag_author_id_fkey', 'cn_tag', type_='foreignkey')
    op.create_foreign_key(None, 'cn_tag', 'cn_account', ['author_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cn_tag', type_='foreignkey')
    op.create_foreign_key('cn_tag_author_id_fkey', 'cn_tag', 'cn_account', ['author_id'], ['id'])
    op.drop_constraint(None, 'cn_note', type_='foreignkey')
    op.create_foreign_key('cn_note_author_id_fkey', 'cn_note', 'cn_account', ['author_id'], ['id'])
    # ### end Alembic commands ###
